### PR TITLE
Add Predictor class

### PR DESCRIPTION
**Pull request by sallamander**
This PR adds a lightweight `Predictor` class that can be used to load the classification / segmentation weights provided by the authors of the paper and perform classification / segmentation on any specified image (provided it's the right shape). @typicalTYLER once we discuss the design decisions and chat a bit further about this design, I'll add some unit tests. 

##  Design decisions to think about: 
- The segmentations aren't currently resized to the image size fed into the model (299 x 299); they're returned as 100 x 100 as output by the model. Should we default to reshaping them in the class itself? I think that would make the most sense. 
- The class itself takes both the classification and segmentation model checkpoints, and automatically loads both. Should we instead have a separate class (or set of functionality) just for classification? Alternatively, we could alter the `dirpath_segmentation_checkpoint` parameter in the `__init__` to default to `None`, and then only load the model if it's passed in. That might make the most sense. 

## Code Snippet to use the `Predictor` and plot some results

Note this requires downloading the models provided by the paper authors, as well as a directory of images to run inference on. Also, you'll need to make sure the `DIRPATH_PLOTS` exists, as the code snippet won't create it for you.  

```
DIRPATH_CLASSIFICATION_CHECKPOINT = [fill in path to classification checkpoint]
DIRPATH_SEGMENTATION_CHECKPOINT = [fill in path to segmentation checkpoint]
DIRPATH_IMAGES = [path to directory of images to run inference on]
DIRPATH_PLOTS = [path to directory to save plots of results in]

IMAGE_SIZE = 299

predictor = Predictor(
    dirpath_classification_checkpoint=DIRPATH_CLASSIFICATION_CHECKPOINT,
    dirpath_segmentation_checkpoint=DIRPATH_SEGMENTATION_CHECKPOINT
)

for fname_image in os.listdir(DIRPATH_IMAGES):
    fpath_image = os.path.join(DIRPATH_IMAGES, fname_image)
    image = skimage.io.imread(fpath_image)
    resized_image = skimage.transform.resize(image, (IMAGE_SIZE, IMAGE_SIZE))
    if resized_image.shape[2] != 3:
        resized_image = resized_image[:, :, 0:3]
    resized_image = resized_image[None, ...]
    
    classification_prob = predictor.classify(resized_image)
    segmentation = predictor.segment(resized_image)
    segmentation = segmentation >= 0.37
    segmentation = skimage.transform.resize(segmentation, (IMAGE_SIZE, IMAGE_SIZE))
    segmentation = segmentation > 0.5
    
    fig, axes = plt.subplots(1, 2)
    resized_image = resized_image[0, ...]
    axes[0].imshow(resized_image)
    axes[0].axis('off')
    axes[1].imshow(segmentation)
    axes[1].axis('off')
    
    fig.suptitle('{:.2f}'.format(classification_prob))
    fname_save = fname_image + '.png'
    fpath_save = os.path.join(DIRPATH_PLOTS, fname_save)
    plt.savefig(fpath_save)
    
    plt.clf()
```

## Example Plots from running that code

The title of the plot is just the predicted probability that the image contains a solar panel. The left subplot is the raw image and the right subplot is the segmentation output, using a threshold of 0.37. The segmentation output is plotted *regardless* of the predicted classification probability. 

image
image
image
image

### CODE REVIEW

**Comment by typicalTYLER** [comment]
@sallamander Nice work! I'll give a cursory pass now from my phone and then run the code once I get access to a computer again.

For the design decisions, outputting the 100x100 segmented image is probably okay for now. It would make sense to let the caller decide what method to use to resize. Also, due to the preprocessing resize the original input image might be something like 320x320 (as it is in our use case), so it might be lossy to go to 299x299 and then 320x320 (Although my intuition could be incorrect). Maybe an optional resize parameter could be passed into the segment method. 

Also, your idea about optional segmentation checkpoint parameter seems ideal. We probably won't run segmentation when first scanning the imagery, and will maybe run it to estimate bounding boxes/wattage estimates once there's some level of confidence about a tile. Although there might be speedup from running them at the same time. I'll have to investigate more. But either way the optional parameter seems like a good idea.

Thanks again! This looks great. Feel free to merge it or add some more to this request if you want to add the design decisions. We can create issues for the follow-up stuff if anything comes up.

**Comment by typicalTYLER** [comment]
I've run the code and it looks good to me! I had a couple of observations and technical questions though:

- I tried running the model with TensorFlow 1.13 but it got some errors, so I downgraded to 1.12 and it worked. So maybe we should add some frozen requirements.
- For the example code, why did you choose 0.37 as the segmentation threshold, was this from the paper?
- Also in the example code, is the line `resized_image = resized_image[None, ...]` basically turning the image into an image batch of size one?

**Comment by sallamander** [comment]
@typicalTYLER thanks for taking a look! I went ahead and added some additional parameters to support (a) only loading the classification model (defaults to not loading the segmentation model) and (b) resizing the target if desired (defaults to not resizing it). 

RE the other stuff: 

> I tried running the model with TensorFlow 1.13 but it got some errors, so I downgraded to 1.12 and it worked. So maybe we should add some frozen requirements.

Yeah, looks like I was running it on TF 1.4 😬 . I'm good with adding some frozen requirements - do you have a preference for a YML (e.g. something [like this](https://github.com/sallamander/dl-playground/blob/master/setup/environment_gpu.yml)) or a `setup.py` file (e.g. something [like this](https://github.com/keras-team/keras/blob/master/setup.py#L35)), or something else? I've always found the YML file approach to work well in the past, but also don't have a ton of experience with the `setup.py` route. I'm happy to set up a YML file if we want to go that route. Shouldn't take long. 

Along these lines, you mentioned Docker at some point - what do you think about putting together some Dockerfiles that people could use to bootstrap the environment? It may be a bit early for this, but people could always opt not to use the Dockerfiles and instead just use the frozen requirements if they want. I've found development in containers to be quite nice when collaborating, particularly just in alleviating the occurrence  of system specific errors, install issues, etc. If we want to do this, I'm also happy to put that together. I've got some existing stuff that I could pull from pretty quickly. 

> For the example code, why did you choose 0.37 as the segmentation threshold, was this from the paper?

Yeah, exactly. It's in the author's repo [here](https://github.com/wangzhecheng/DeepSolar/blob/master/test_segmentation.py#L37). 

> Also in the example code, is the line resized_image = resized_image[None, ...] basically turning the image into an image batch of size one

Yeah. In the future I should probably use `expand_dims`, as that might be a bit more clear. 

I haven't written tests yet, but I'm going to go ahead and merge. I worry a bit about putting in the effort before we have a testing environment / plan (e.g. something like CI) figured out. Do you have any thoughts on that?

**Comment by typicalTYLER** [comment]
@sallamander RE frozen reqs, YML works for me. I'm more familiar with setup.py and venv (but I think I'm stuck in a local maximum, the consensus seems to be conda is better), but as we have no intention of making this a pip package, YML seems like the better choice.

RE docker files, this sounds like a great idea! I've been kind of implementing things moderately greedily to get to a working prototype [(Here's some results!)](https://twitter.com/TylerBusby333/status/1112564591400239105). So the package management is likely very brittle. I think to run my inference code submitted [here](https://github.com/typicalTYLER/SolarPanelDataWrangler/commit/88175ad52cfcda954233057e49d12c7df8287584), you have to have DeepSolar and SPDW both loaded into pycharm as attached projects. So dockerization seems like a good next step.

I'm not sure if the current repo structure is the optimal way to do it, but maybe putting them both in docker can eliminate some of the overhead of keeping them separate. For example, in my linked code above, I'm passing the checkpoint directories as script arguments to the run_inference.py script inside of SPDW, which seems to be breaking some sort of best practice, but I'm not sure what. I've thought about keeping DeepSolar just inside SPDW, but that seems to be too tightly coupling everything together. Especially if people want to retrain DeepSolar by itself on different data, I think [Damien](https://twitter.com/dctanner) might be doing this atm for UK data. Unsure if he's using this repo directly though.

Another consideration I might mention here, I want people to be able to plug in different models/frameworks to SDPW. Just because there was talk of using fast.ai to reimplement DeepSolar, and there was another paper called SolarMapper that we might trial as well for different areas/data. This might affect some design decisions, but it's unclear to what extent it will be necessary. I'd hate to spend a lot of time overgeneralizing as well, as there's lots of [other projects](https://docs.google.com/document/d/14UZd_qdAjD8P1VGNQThf3rZz9tBCXk2_ySZ_oNIEdSs/edit) that will need attention too.

Maybe putting the docker configuration in SPDW, and just the YML in this repo would be a good starting point? Although a DeepSolar only docker container might be worthwhile for standalone development on it.

RE segmentation threshold, interesting, I wonder if that threshold is theoretical or practical, I'll have to look at their paper again.

RE testing, I don't have much experience with GitHub CI options, or unit testing tensorflow models, but definitely if we're past the prototype milestone it seems like a good idea to make an effort to test. I'm open to any ideas in that domain! Feel free to create issues or explore whatever you think is best.

Again, thanks so much for helping out!

**Comment by sallamander** [comment]
It sounds like it might be a bit too early to do any serious work on packaging, but maybe it's worth a larger discussion with Damien (don't know what his GH handle is) to figure out overall goals and / or next steps? If a prototype is all we're after for right now, then I don't know that it's worth significantly more investment in some of these things. But, it sounds like there is a desire for something that will allow others to get easily spun up, contribute, etc., in which case I think there are a number of things we could move forward with (packaging, testing, etc.). 

I'm not sure what the best move is in terms of repository structure, but I could see how a single repository for all of the solar panel data wrangling (across multiple datasets) as well as all of the modeling code (fastai or otherwise) could work well. We could simply have different directories for modeling versus data wrangling. I think there is likely to be heavy overlap between environments as well as code (e.g. the pre and post-processing steps for modeling training & inference) that it might be more of a pain to keep things separated and build out tooling to pull it all together in a single environment than to simply store things in a single repo. An added benefit is that with a single repo it's much easier for people to find everything since it's co-located. 

RE the testing, I think this depends on future goals. If we want to continue moving past the prototype stage (and it sounds like to some degree we do), then I think it's worth it. But, I also think it'd be great to do some small amount of planning (maybe even just a quick chat over hangouts or something) before moving forward with a lot of this stuff.

**Comment by typicalTYLER** [comment]
Agreed. We should definitely schedule some sort of discussion, I know Damien mentioned scheduling a wider one (we talked once previously before you joined in), and I think it's doubly overdue now that a prototype is finished and we haven't heard from Jack in a while.

I know we definitely eventually want more than a prototype, that was just my immediate goal to verify that the DeepSolar pre-trained weights worked well on MapBox data in the US. And having a prototype will allow us to investigate the human verification pipeline more, and give us some data to fill it up, in case human verification takes a long time.

The word from Damien is that OpenClimateFix is going to focus the first big solar nowcasting experiment in the UK, but I've been receiving positive feedback from everybody about locating solar panels in the US and working on this project. So we decided that I'd keep at this and Damien would attempt to build a UK specific training set for transfer learning/retraining. I imagine once inference is ran on the whole country it will be using this project but with a different imagery source (MapBox isn't great in the UK). But it would be good to sync back up and re-prioritize things.

**Comment by sallamander** [comment]
Ah, good information, thanks for passing it on! 

Would you mind looping me when you have this discussion, and / or just passing on the results? I'd love to keep helping out once things are re-prioritized and the most helpful next steps are determined.

**Comment by typicalTYLER** [comment]
Definitely! I know Jack was working on setting up a discourse instance for OpenClimateFix, but I'll definitely loop you in when we have further discussions.

**Comment by sallamander** [comment]
Awesome, thanks! In the meantime I think I'm going to try to get started on some of the cloud cover modeling.

**Pull request merged**
